import { defineConfig } from "vitepress";

const base = process.env.VITEPRESS_BASE || "/";
const siteUrl = "https://wdkang123.github.io/ai-infra-handbook/";

export default defineConfig({
  lang: "zh-CN",
  title: "AI Infra Handbook",
  description: "把学习文档、可运行脚手架、hands-on labs 和最小联调链路收成一个可浏览的 AI Infra 学习站。",
  base,
  cleanUrls: true,
  lastUpdated: true,
  ignoreDeadLinks: "localhostLinks",
  head: [
    ["meta", { property: "og:title", content: "AI Infra Handbook" }],
    [
      "meta",
      {
        property: "og:description",
        content: "一套能边学边跑的 AI Infra 学习站，覆盖推理服务、AI Gateway、评测观测、微调训练和公开分享材料。",
      },
    ],
    ["meta", { property: "og:type", content: "website" }],
    ["meta", { property: "og:url", content: siteUrl }],
    ["meta", { name: "twitter:card", content: "summary" }],
  ],
  themeConfig: {
    siteTitle: "AI Infra Handbook",
    logo: {
      src: "/mark.svg",
      alt: "AI Infra Handbook",
    },
    search: {
      provider: "local",
    },
    nav: [
      {
        text: "开始",
        items: [
          { text: "从 0 到 1", link: "/00-overview/00-zero-to-one" },
          { text: "学习路线", link: "/00-overview/02-learning-route" },
          { text: "第一次实操", link: "/00-overview/04-first-walkthrough" },
          { text: "两周学习计划", link: "/00-overview/15-two-week-learning-plan" },
          { text: "运行手册", link: "/00-overview/03-runbook" },
        ],
      },
      {
        text: "系统模块",
        items: [
          { text: "基础概念", link: "/01-llm-fundamentals/00-overview" },
          { text: "推理服务", link: "/02-inference-serving/00-overview" },
          { text: "平台层", link: "/03-ai-gateway-platform/00-overview" },
          { text: "评测与观测", link: "/04-evaluation-observability/00-overview" },
          { text: "微调训练", link: "/05-finetuning-training/00-overview" },
        ],
      },
      {
        text: "实践",
        items: [
          { text: "深度实战", link: "/07-hands-on-labs/00-overview" },
          { text: "示例输出", link: "/13-output-gallery/00-overview" },
          { text: "共学套件", link: "/14-workshop-kit/00-overview" },
          { text: "案例复盘", link: "/11-case-studies/00-overview" },
          { text: "学习自测", link: "/10-assessments/00-overview" },
          { text: "生产迁移", link: "/12-production-migration/00-overview" },
        ],
      },
      {
        text: "发布与参考",
        items: [
          { text: "公开发布", link: "/08-publication/00-overview" },
          { text: "参考资料", link: "/09-reference/00-overview" },
          { text: "验证矩阵", link: "/09-reference/07-validation-matrix" },
          { text: "学习站清单", link: "/09-reference/08-learning-inventory" },
          { text: "发布摘要", link: "/09-reference/09-release-brief" },
          { text: "课程目录", link: "/09-reference/10-course-catalog" },
          { text: "路线图包", link: "/08-publication/05-generated-roadmap-pack" },
          { text: "仓库卫生规范", link: "/08-publication/06-public-repo-hygiene" },
          { text: "依赖维护", link: "/08-publication/07-dependency-maintenance" },
          { text: "维护节奏", link: "/08-publication/08-maintainer-rhythm" },
          { text: "Issue 分类", link: "/08-publication/09-issue-triage-and-labels" },
          { text: "v0.1 发布", link: "/08-publication/10-v0-1-release-playbook" },
          { text: "首批 Issues", link: "/08-publication/11-first-public-issues" },
          { text: "Release Notes 草稿", link: "/08-publication/12-v0-1-release-notes-draft" },
          { text: "首发运营包", link: "/08-publication/13-generated-launch-pack" },
        ],
      },
    ],
    sidebar: [
      {
        text: "总览",
        items: [
          { text: "首页", link: "/" },
          { text: "从 0 到 1 学习路径", link: "/00-overview/00-zero-to-one" },
          { text: "什么是 AI Infra", link: "/00-overview/01-what-is-ai-infra" },
          { text: "学习路线图", link: "/00-overview/02-learning-route" },
          { text: "最小运行手册", link: "/00-overview/03-runbook" },
          { text: "第一次实操演练", link: "/00-overview/04-first-walkthrough" },
          { text: "文档与代码怎么对应", link: "/00-overview/05-docs-to-code-map" },
          { text: "第一次跑完之后学什么", link: "/00-overview/06-after-first-walkthrough" },
          { text: "按目标选择学习路径", link: "/00-overview/07-choose-your-path" },
          { text: "常见学习误区", link: "/00-overview/08-common-learning-mistakes" },
          { text: "学习检查点", link: "/00-overview/09-learning-checkpoints" },
          { text: "常见问题 FAQ", link: "/00-overview/10-faq" },
          { text: "面向分享的学习方式", link: "/00-overview/11-public-learning-guide" },
          { text: "课程大纲", link: "/00-overview/12-course-syllabus" },
          { text: "术语索引", link: "/00-overview/13-glossary" },
          { text: "项目成熟度地图", link: "/00-overview/14-project-maturity-map" },
          { text: "两周学习计划", link: "/00-overview/15-two-week-learning-plan" },
        ],
      },
      {
        text: "项目学习",
        items: [
          { text: "项目总览", link: "/06-projects/00-projects-overview" },
          { text: "inference-service", link: "/06-projects/01-inference-service" },
          { text: "ai-gateway", link: "/06-projects/02-ai-gateway" },
          { text: "eval-module", link: "/06-projects/03-eval-module" },
          { text: "finetune-demo", link: "/06-projects/04-finetune-demo" },
          { text: "文档与项目怎么联动", link: "/06-projects/05-docs-and-projects-map" },
          { text: "四个项目怎么连成系统", link: "/06-projects/06-end-to-end-system-map" },
          { text: "质量与维护入口", link: "/06-projects/07-quality-and-maintenance" },
        ],
      },
      {
        text: "01 LLM Fundamentals",
        items: [
          { text: "总览", link: "/01-llm-fundamentals/00-overview" },
          { text: "模型、Token、Context", link: "/01-llm-fundamentals/01-model-token-context" },
          { text: "Prefill、Decode、KV Cache", link: "/01-llm-fundamentals/02-prefill-decode-kv-cache" },
          { text: "TTFT、ITL、吞吐", link: "/01-llm-fundamentals/03-ttft-itl-throughput" },
          { text: "从请求到首个 Token", link: "/01-llm-fundamentals/04-from-request-to-first-token" },
        ],
      },
      {
        text: "02 Inference Serving",
        items: [
          { text: "总览", link: "/02-inference-serving/00-overview" },
          { text: "vLLM 与 SGLang", link: "/02-inference-serving/01-vllm-sglang" },
          { text: "Triton 与 TensorRT-LLM", link: "/02-inference-serving/02-triton-tensorrt-llm" },
          { text: "服务选型与取舍", link: "/02-inference-serving/03-serving-tradeoffs" },
          { text: "vLLM", link: "/02-inference-serving/04-vllm" },
          { text: "SGLang", link: "/02-inference-serving/05-sglang" },
          { text: "Cache 与 Prefix Caching", link: "/02-inference-serving/06-cache-prefix-caching" },
          { text: "Triton Inference Server", link: "/02-inference-serving/07-triton-inference-server" },
          { text: "TensorRT-LLM", link: "/02-inference-serving/08-tensorrt-llm" },
          { text: "Streaming、Batching、Metrics", link: "/02-inference-serving/09-streaming-batching-metrics" },
          { text: "从学习型服务到真实 Serving Stack", link: "/02-inference-serving/10-from-learning-service-to-real-serving-stack" },
        ],
      },
      {
        text: "03 AI Gateway Platform",
        items: [
          { text: "总览", link: "/03-ai-gateway-platform/00-overview" },
          { text: "鉴权、路由、限流", link: "/03-ai-gateway-platform/01-auth-routing-rate-limit" },
          { text: "健康检查、Metrics、Request ID", link: "/03-ai-gateway-platform/02-health-metrics-request-id" },
          { text: "Gateway、Router、Fallback、Cache", link: "/03-ai-gateway-platform/03-gateway-router-fallback-cache" },
          { text: "Streaming、错误路径、Upstream Health", link: "/03-ai-gateway-platform/04-streaming-errors-upstream-health" },
          { text: "平台层与模型服务层边界", link: "/03-ai-gateway-platform/05-platform-vs-model-service" },
          { text: "外部模型名与内部目标映射", link: "/03-ai-gateway-platform/06-model-name-to-target-mapping" },
          { text: "从 Demo Gateway 到真实平台", link: "/03-ai-gateway-platform/07-from-demo-gateway-to-real-platform" },
        ],
      },
      {
        text: "04 Evaluation Observability",
        items: [
          { text: "总览", link: "/04-evaluation-observability/00-overview" },
          { text: "Run、Compare、History", link: "/04-evaluation-observability/01-run-compare-history" },
          { text: "Benchmark、Leaderboard、Observability", link: "/04-evaluation-observability/02-benchmark-leaderboard-observability" },
          { text: "Tracing、Metrics、Logs", link: "/04-evaluation-observability/03-observability-traces-metrics-logs" },
          { text: "评测工具与展示面", link: "/04-evaluation-observability/04-evaluation-tools-and-surfaces" },
          { text: "LLM Evaluation", link: "/04-evaluation-observability/05-llm-evaluation" },
          { text: "Benchmark、Arena、Leaderboard", link: "/04-evaluation-observability/06-benchmark-arena-leaderboard" },
          { text: "从 Run 到发布决策", link: "/04-evaluation-observability/07-from-run-to-release-decision" },
          { text: "Benchmark 与生产质量不是一回事", link: "/04-evaluation-observability/08-benchmark-vs-production-quality" },
        ],
      },
      {
        text: "05 Finetuning Training",
        items: [
          { text: "总览", link: "/05-finetuning-training/00-overview" },
          { text: "LoRA、QLoRA、PEFT", link: "/05-finetuning-training/01-lora-qlora-peft" },
          { text: "训练产物、Checkpoint、Export", link: "/05-finetuning-training/02-run-artifacts-export" },
          { text: "Unsloth 与训练栈", link: "/05-finetuning-training/03-unsloth-training-stack" },
          { text: "数据集、Run、Checkpoint", link: "/05-finetuning-training/04-datasets-runs-checkpoints" },
          { text: "SFT、DPO 与训练目标", link: "/05-finetuning-training/05-sft-dpo-and-training-objectives" },
          { text: "实验追踪、History、复现", link: "/05-finetuning-training/06-experiment-tracking-history-reproducibility" },
          { text: "什么时候该微调", link: "/05-finetuning-training/07-when-to-finetune" },
          { text: "从 Demo Training 到真实训练系统", link: "/05-finetuning-training/08-from-demo-training-to-real-training-system" },
        ],
      },
      {
        text: "07 Hands-on Labs",
        items: [
          { text: "深度实战总览", link: "/07-hands-on-labs/00-overview" },
          { text: "Serving 可观测性 Lab", link: "/07-hands-on-labs/01-serving-observability-lab" },
          { text: "Gateway 韧性 Lab", link: "/07-hands-on-labs/02-gateway-resilience-lab" },
          { text: "Eval 发布门禁 Lab", link: "/07-hands-on-labs/03-eval-release-gate-lab" },
          { text: "Finetune 复现资产 Lab", link: "/07-hands-on-labs/04-finetune-reproducibility-lab" },
          { text: "系统 Capstone 与验收 Rubric", link: "/07-hands-on-labs/05-capstone-review-rubric" },
          { text: "公开发布验收 Lab", link: "/07-hands-on-labs/06-public-release-readiness-lab" },
        ],
      },
      {
        text: "11 Case Studies",
        items: [
          { text: "案例复盘总览", link: "/11-case-studies/00-overview" },
          { text: "请求失败排查案例", link: "/11-case-studies/01-request-incident-walkthrough" },
          { text: "模型发布判断案例", link: "/11-case-studies/02-model-release-decision-walkthrough" },
          { text: "训练产物复现案例", link: "/11-case-studies/03-finetune-to-eval-asset-lineage" },
          { text: "Gateway Fallback 与缓存复盘案例", link: "/11-case-studies/04-gateway-fallback-cache-incident" },
          { text: "Eval 退化与发布阻断案例", link: "/11-case-studies/05-eval-regression-release-gate" },
        ],
      },
      {
        text: "13 Output Gallery",
        items: [
          { text: "示例输出总览", link: "/13-output-gallery/00-overview" },
          { text: "Serving 与 Gateway 输出证据", link: "/13-output-gallery/01-serving-gateway-evidence" },
          { text: "Eval 报告证据", link: "/13-output-gallery/02-eval-report-evidence" },
          { text: "Finetune 产物证据", link: "/13-output-gallery/03-finetune-artifact-evidence" },
          { text: "端到端复盘证据包", link: "/13-output-gallery/04-end-to-end-review-packet" },
          { text: "失败症状到证据地图", link: "/13-output-gallery/05-failure-evidence-map" },
          { text: "公开演示脚本", link: "/13-output-gallery/06-public-demo-script" },
          { text: "自动生成证据包", link: "/13-output-gallery/07-generated-evidence-packet" },
        ],
      },
      {
        text: "14 Workshop Kit",
        items: [
          { text: "共学与公开分享套件", link: "/14-workshop-kit/00-overview" },
          { text: "讲师与带练指南", link: "/14-workshop-kit/01-facilitator-guide" },
          { text: "学习者工作簿", link: "/14-workshop-kit/02-learner-workbook" },
          { text: "学习小组议程", link: "/14-workshop-kit/03-study-group-agenda" },
          { text: "复盘与评审模板", link: "/14-workshop-kit/04-review-templates" },
          { text: "贡献者协作手册", link: "/14-workshop-kit/05-contribution-playbook" },
          { text: "GitHub 发布计划", link: "/14-workshop-kit/06-github-release-plan" },
          { text: "自动生成共学包", link: "/14-workshop-kit/07-generated-workshop-packet" },
        ],
      },
      {
        text: "12 Production Migration",
        items: [
          { text: "生产迁移路线总览", link: "/12-production-migration/00-overview" },
          { text: "Serving 后端迁移", link: "/12-production-migration/01-serving-backend-migration" },
          { text: "Gateway 平台化加固", link: "/12-production-migration/02-gateway-platform-hardening" },
          { text: "Eval 评测系统迁移", link: "/12-production-migration/03-eval-judge-dashboard-migration" },
          { text: "Finetune 真实训练迁移", link: "/12-production-migration/04-finetune-real-training-migration" },
        ],
      },
      {
        text: "08 Publication",
        items: [
          { text: "公开发布总览", link: "/08-publication/00-overview" },
          { text: "GitHub Pages 发布指南", link: "/08-publication/01-github-pages" },
          { text: "内容写作规范", link: "/08-publication/02-content-style-guide" },
          { text: "公开路线图", link: "/08-publication/03-public-roadmap" },
          { text: "GitHub 仓库设置建议", link: "/08-publication/04-repository-settings" },
          { text: "自动生成路线图包", link: "/08-publication/05-generated-roadmap-pack" },
          { text: "公开仓库卫生规范", link: "/08-publication/06-public-repo-hygiene" },
          { text: "依赖维护与 Bot PR 处理", link: "/08-publication/07-dependency-maintenance" },
          { text: "维护节奏与运营清单", link: "/08-publication/08-maintainer-rhythm" },
          { text: "Issue 分类与标签策略", link: "/08-publication/09-issue-triage-and-labels" },
          { text: "v0.1 首发发布手册", link: "/08-publication/10-v0-1-release-playbook" },
          { text: "首批公开 Issues 草稿", link: "/08-publication/11-first-public-issues" },
          { text: "v0.1 Release Notes 草稿", link: "/08-publication/12-v0-1-release-notes-draft" },
          { text: "自动生成首发运营包", link: "/08-publication/13-generated-launch-pack" },
        ],
      },
      {
        text: "09 Reference",
        items: [
          { text: "参考资料总览", link: "/09-reference/00-overview" },
          { text: "命令速查", link: "/09-reference/01-command-cheatsheet" },
          { text: "概念到代码索引", link: "/09-reference/02-concept-to-code-index" },
          { text: "产物与文件索引", link: "/09-reference/03-artifacts-and-files" },
          { text: "常见排障手册", link: "/09-reference/04-troubleshooting" },
          { text: "API Surface 速查", link: "/09-reference/05-api-surface" },
          { text: "CLI Surface 速查", link: "/09-reference/06-cli-surface" },
          { text: "验证矩阵", link: "/09-reference/07-validation-matrix" },
          { text: "学习站清单生成器", link: "/09-reference/08-learning-inventory" },
          { text: "发布摘要生成器", link: "/09-reference/09-release-brief" },
          { text: "课程目录生成器", link: "/09-reference/10-course-catalog" },
        ],
      },
      {
        text: "10 Assessments",
        items: [
          { text: "学习自测总览", link: "/10-assessments/00-overview" },
          { text: "系统地图自测", link: "/10-assessments/01-system-map-check" },
          { text: "Serving 与 Gateway 自测", link: "/10-assessments/02-serving-gateway-quiz" },
          { text: "Eval 与 Finetune 自测", link: "/10-assessments/03-eval-finetune-quiz" },
          { text: "Capstone 答辩稿", link: "/10-assessments/04-capstone-defense" },
          { text: "参考答案与讲解", link: "/10-assessments/05-answer-key" },
          { text: "自动生成测评包", link: "/10-assessments/06-generated-assessment-pack" },
        ],
      },
    ],
    outline: {
      level: [2, 3],
    },
    footer: {
      message: "Learning-first docs + runnable scaffold.",
      copyright: "AI Infra Handbook",
    },
  },
});
